#!/usr/bin/env fish

# Demo script to show the decorated fish prompt
echo "🐟 Fish Shell Prompt Decoration Demo"
echo "===================================="
echo ""
echo "Your fish shell has been decorated with:"
echo ""
echo "✨ Features:"
echo "  🕐 Current time display"
echo "  🚀 User and hostname with icons"
echo "  📁 Smart directory icons (📚 for bash learning, 🏠 for home, etc.)"
echo "  🌿 Git branch and status indicators:"
echo "     🌿 Clean repository"
echo "     🔥 Uncommitted changes"
echo "     ⚡ Staged changes"
echo "     💥 Merge conflicts"
echo "  ✅/❌ Command success/failure indicators"
echo "  🐟 Beautiful prompt symbol"
echo ""
echo "🎨 Customization Commands:"
echo "  toggle_minimal_prompt  - Switch between decorated and minimal styles"
echo "  fish_themes           - Show available customization options"
echo "  git-status-pretty     - Beautiful git status display"
echo "  edit-fish-config      - Edit fish configuration"
echo ""
echo "🔄 To see the new prompt:"
echo "  1. Open a new terminal (fish will be default)"
echo "  2. Or type: exec fish"
echo "  3. Or restart your current session"
echo ""
echo "Example of what your prompt will look like:"
echo ""
echo "╭─🕐 15:30 ─ 🚀 xe@localhost ─ 📚 ~/linux-cli-scripting ─ 🌿 main ─ ✅"
echo "╰─🐟 "
echo ""
echo "Happy coding with your beautiful fish shell! 🎉"
